[project]
name = "nn-magnetics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "magpylib-material-response>=0.3.0",
    "magpylib>=5.1.1",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "torch>=2.5.1",
    "tqdm>=4.67.0",
    "wandb>=0.18.6",
]
